### ISSUE TITLE
Renumbering 

### ISSUE THREAD

**Issue by harryhaaren** [harryhaaren/showq#10]
A strange thing happens when renumbering the show. All cue id's and target id's are set to 0. But looking at the xml-file shows that renumbering works a bit. The fourth (fade)cue in my list, which was before cue id 7, targeting cue 5, now reads:
<cue type="Fade" id="4">
<cue_id>0</cue_id>
<Fade target="3" .....

( from http://sourceforge.net/p/showq/tickets/4/ )

**Comment by sonik22** [comment]
I confirm its working.
