### ISSUE TITLE
unable to launch ShowQ built from GIT 4700ddc

### ISSUE THREAD

**Issue by trebmuh** [harryhaaren/showq#29]
Build from today's GIT https://github.com/evandelisle/showq/commit/4700ddcd865d98aa6a2bd35bf4585034f4675c18 , the build is going fine, but when trying to launch showq, I've got:

```
$ showq
ShowQ:out_1 # system:playback_1
ShowQ:out_2 # system:playback_2
ShowQ:out_3 # a2j:Midi Through [14] (playback): Midi Through Port-0
ShowQ:out_4 # PulseAudio JACK Source:front-left
ShowQ:out_5 # PulseAudio JACK Source:front-right
```

![showq-error](https://cloud.githubusercontent.com/assets/8705846/18182530/a8255bb6-7090-11e6-8f6e-84ce00ed9454.png)
Then, when clicking on the OK button, nothing happen but showq finishing.

@evandelisle : let me know if I could provide any other information.

**Comment by evandelisle** [comment]
The line

> ShowQ:out_3 # a2j:Midi Through [14](playback): Midi Through Port-0
> is a bit odd. ShowQ should only connect to audio ports, but that looks like a MIDI port.
> If you try without the Jack MIDI would you get the same result?

The problem could be that ShowQ is connecting to Jack ports and does not care if they are audio or MIDI.

**Comment by trebmuh** [comment]
Hi @evandelisle 

just to let you know that trying with the debian sid package backported to debian jessie, which is a built from git 2015 september 03, I get exactly the same:

```
ShowQ:out_1 # system:playback_1
ShowQ:out_2 # system:playback_2
ShowQ:out_3 # a2j:Midi Through [14] (playback): Midi Through Port-0
ShowQ:out_4 # PulseAudio JACK Source:front-left
ShowQ:out_5 # PulseAudio JACK Source:front-right
```

but ShowQ opens and I can use it. Ie: no "ShowQ encountered an unknown error".

I'll try to find some time to test without the jack-MIDI as you suggested.

Hope that helps.

**Comment by trebmuh** [comment]
Hi @evandelisle , using showq from debian stretch which is build from [GIT 20161215](https://anonscm.debian.org/cgit/pkg-multimedia/showq.git), I still have the same issue and the terminal still says:
```
$ showq 
ShowQ:out_1 # system:playback_1
ShowQ:out_2 # system:playback_2
ShowQ:out_3 # PulseAudio JACK Source:front-left
ShowQ:out_4 # PulseAudio JACK Source:front-right
```
Then:
![showq-error](https://cloud.githubusercontent.com/assets/8705846/18182530/a8255bb6-7090-11e6-8f6e-84ce00ed9454.png)

Anything I can help you with, please let me know.

**Comment by nsprangers** [comment]
Similar issue with Ubuntu 17.10 (package version 0.4.1+git20161215~dfsg0-2ubuntu1)

`$ showq`
`ShowQ:out_1 # system:playback_1`
`ShowQ:out_2 # system:playback_2`

However, building showq from current git source launches without this error on Ubuntu 17.10. This suggests to me that this is a Debian bug, not a showq bug.

I see that @trebmuh has already submitted a bug to Debian. I will add a comment there that the solution may be simply to update the package to current source.

**Comment by trebmuh** [comment]
[debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883636)

**Comment by trebmuh** [comment]
@evandelisle the bug is on its way to get workarounded on the Debian side, thanks to James Cowgill. That said, if you're to read [his comment](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883636), it could be fixed in the code (which sounds to be better).

Hope that helps, and happy new year to you and yours.
