### ISSUE TITLE
Crash if a m4a is imported

### ISSUE THREAD

**Issue by mitscherdinger** [harryhaaren/showq#30]
Hey, it's not a bug, it's a feature!

Haven't tried this with other audio-files not supported by showq, but if you try to import a m4a-file (no matter if drag n drop or using edit -> new cue -> wave cue, showq crashes. Would be nice, if showq says "not supported" insteas of crashing... :)

**Comment by evandelisle** [comment]
Confirmed, does not matter what the file is.
