### ISSUE TITLE
i Can't install the program ...

### ISSUE THREAD

**Issue by El-Brouno** [harryhaaren/showq#36]
Hello,

I would like to try SHOWQ on my ubuntu 16.04 distribution but the ./waf configure give 

>  Logged from file Logs.py, line 167
> Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
> Checking for program 'pkg-config'        : /usr/bin/pkg-config 
> Checking for pkg-config version >= '0.0.0' : yes 
> Checking for 'gtkmm-2.4'                   : yes 
> Checking for 'gthread-2.0'                 : yes 
> Checking for 'libxml++-2.6'                : yes 
> Checking for 'alsa'                        : yes 
> Checking for 'jack'                        : not found 
> The configuration failed
> (complete log in /home/bruno/Téléchargements/showq/build/config.log) 

When i'm looking in the " config.log " file, i can read this at the end :

> Checking```for 'jack'
> ['/usr/bin/pkg-config', '--cflags', '--libs', 'jack']
> err: Package jack was not found in the pkg-config search path.
> Perhaps you should add the directory containing `jack.pc'`
> to the PKG_CONFIG_PATH environment variable
> No package 'jack' found
> 
> not found
> from /home/bruno/Téléchargements/showq/src: The configuration failed 

Can you give me some help please ?
I always installed JACK and used it with Ardour ou LISP without no matter.

Thank you
Bruno

**Comment by trebmuh** [comment]
You need the dev package for jack which is `libjack-dev` or `libjack-jackd2-dev`.

**Comment by El-Brouno** [comment]
Perfect !!! 
Thank you and have a nice night.
Bruno

**Comment by trebmuh** [comment]
You're welcome. @El-Brouno : please close this issue if that's done for you. Merci.
