### ISSUE TITLE
Fade time is not saved correctly 

### ISSUE THREAD

**Issue by harryhaaren** [harryhaaren/showq#7]
Fade times having values after the point are not saved correctly. 0,5 sec is saved as zero, 3,2 sec is saved as 3 sec. Manually editing the xml-file is possible, fade times are recalled correctly as long as the file isn't saved again. 

( from http://sourceforge.net/p/showq/tickets/1/ )

**Comment by sonik22** [comment]
This happens when the locales use the "," as separator and not the "."
To use it on a french system (my case), you can change the Exec-Line in the desktop-file to:
Exec=env LANG="C" showq
or you can start showq in the terminal with:
 LANG="C" showq
